### ISSUE TITLE
How to use Provider pattern only

### ISSUE THREAD

**Issue by premtemp1** [bizz84/firebase_auth_demo_flutter#7]
Thanks for the articles.. 

This is not a bug but I am not sure how to ask the question,,,

I am not using BLOC pattern, It is too complex for my project .. Do you have a similar article using just provider pattern..

Thanks

**Comment by bizz84** [comment]
I don't have an article for this just yet but I plan to write one.

I have just converted this project to use ValueNotifier/ChangeNotifier instead of BLoCs, which is simpler.

This diff shows the difference between the two approaches: https://github.com/bizz84/firebase_auth_demo_flutter/pull/5/files

**Comment by premtemp1** [comment]
@bizz84 .. Thanks for your help..

Is it possible to do an article on how to make Material bottom navigation bar works like Cupertino. Basically, I have 1 page with 2 bottom navigation item (P1,P2).. Then on page P1, I have. couple of buttons that go to sub pages  (S11,S12).. When the user click on S11, they go to that page but P1 bottom navigation bar should be active.. Currently , when I go to S11 , I lose the navigation..  Thanks
